apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: rancher-chaos
  namespace: sock-shop
spec:
  # It can be true/false
  annotationCheck: 'true'
  engineState: 'active'
  #ex. values: sock-shop:name=carts
  auxiliaryAppInfo: ""
  # It can be delete/retain
  jobCleanUpPolicy: delete
  monitoring: true
  appinfo:
    appns: sock-shop
    # FYI, To see app label, apply kubectl get pods --show-labels
    # unique-label of the application under test (AUT)
    applabel: "name=carts-db"
    appkind: deployment
  chaosServiceAccount: sock-shop-chaos-engine
  experiments:
    - name: container-kill
      spec:
        components:
          env:
            - name: TARGET_CONTAINER
              value: carts-db
            - name: DEFAULT_GATHERING
              value: "explicit"
            - name: LIB_IMAGE  
              value: 'litmuschaos/go-runner:latest'               
            - name: LIB
              value: 'litmus'
            - name: CHAOS_INTERVAL
              value: '10'
            - name: TOTAL_CHAOS_DURATION
              value: '50'

