apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: carts-network-delay
spec:
  annotationCheck: 'true'
  action: delay # the specific chaos action to inject
  mode: one # the mode to run chaos action; supported modes are one/all/fixed/fixed-percent/random-max-percent
  selector: # pods where to inject chaos actions
    namespaces:
      - sock-shop
    labelSelectors:
       "name": carts # the label of the pod for chaos injection
  delay:
    latency: "10ms"
  duration: "30s" # duration for the injected chaos experiment
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 60s"