apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-example
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      "name": front-end
    namespaces:
      - sock-shop
  scheduler:
    cron: "@every 1m"
