apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: kind-chaos
  namespace: sock-shop
spec:
  # It can be true/false
  annotationCheck: 'true'
  #ex. values: sock-shop:name=carts
  auxiliaryAppInfo: ""
  engineState: 'active'
  # It can be delete/retain
  jobCleanUpPolicy: delete
  monitoring: true
  appinfo:
    appns: sock-shop
    # FYI, To see app label, apply kubectl get pods --show-labels
    # unique-label of the application under test (AUT)
    applabel: "name=carts-db"
    appkind: deployment
  chaosServiceAccount: sock-shop-chaos-engine
  experiments:
    - name: disk-fill
      spec:
        components:
          env:
            - name: TARGET_CONTAINER
              value: "carts-db"
            # specify the fill percentage according to the disk pressure required
            - name: FILL_PERCENTAGE
              value: "80"
            # 5 minute duration in seconds
            - name: TOTAL_CHAOS_DURATION
              value: "60"
            - name: DEFAULT_GATHERING
              value: "explicit"
            # Provide the container runtime path
            # Default set to docker
            - name: CONTAINER_PATH
              value: '/var/lib/docker/containers'              
