apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: kind-chaos
  namespace: sock-shop
spec:
  # It can be true/false
  annotationCheck: 'true'
  #ex. values: sock-shop:name=carts
  auxiliaryAppInfo: ""
  engineState: 'active'
  # It can be delete/retain
  jobCleanUpPolicy: delete
  monitoring: true
  appinfo:
    appns: sock-shop
    # FYI, To see app label, apply kubectl get pods --show-labels
    # unique-label of the application under test (AUT)
    applabel: "name=carts-db"
    appkind: deployment
  chaosServiceAccount: sock-shop-chaos-engine
  experiments: 
    - name: node-cpu-hog
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '60'
            
            - name: NODE_CPU_CORE
              value: '2'
  