apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: kind-chaos
  namespace: sock-shop
spec:
  # It can be true/false
  annotationCheck: 'false'
  #ex. values: sock-shop:name=carts
  auxiliaryAppInfo: ""
  engineState: 'active'
  # It can be delete/retain
  jobCleanUpPolicy: delete
  monitoring: true
  appinfo:
    appns: sock-shop
    # FYI, To see app label, apply kubectl get pods --show-labels
    # unique-label of the application under test (AUT)
    applabel: "name=carts-db"
    appkind: deployment
  chaosServiceAccount: sock-shop-chaos-engine
  experiments:
    - name: pod-memory-hog
      spec:
        components:
          env:
            # Provide name of target container
            # where chaos has to be injected
            - name: TARGET_CONTAINER
              value: 'carts-db'

            # Enter the amount of memory in megabytes to be consumed by the application pod
            # default: 500 (Megabytes) 
            - name: MEMORY_CONSUMPTION
              value: '500'

            - name: TOTAL_CHAOS_DURATION
              value: '60' # in seconds

            - name: CHAOS_KILL_COMMAND
              value: "kill -9 $(ps afx | grep \"[dd] if /dev/zero\" | awk '{print $1}' | tr '\n' ' ')"              
